# mgplus workflow

name: CI
env:
  AZURE_STORAGE_SERVICE_ENDPOINT: https://stevodocs.blob.core.windows.net/
  AZURE_STORAGE_AUTH_MODE: login
  AZURE_STORAGE_ACCOUNT_NAME: stevodocs
  AZURE_INDEX_DOCUMENT_NAME: index.html
  SOURCE_DIR: ./dist
on:
  push:
    tags:
      - v*.*.*
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master 
jobs:
  # deploy pullrequest version of demo site
  deploy_pullrequest:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'    
    runs-on: ubuntu-latest
    name: build and deploy PR version
    permissions:
      contents: read            
      id-token: write 
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: "build main css library"
        run: |
          npm install 
          npm run build --if-present
          npm run test --if-present 
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: "build demo app"
        run: |
          cd dom-plugins && npm install 
          npm run build --if-present
          npm run test --if-present  
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true 
      - name: deploy demo app to Azure static website
        uses: azure/CLI@v1     
        env: 
         ACCOUNT_NAME: stevodocs
         DEMO_ROOT_DIR : "$web"         
         DEMO_SOURCE_DIR : tmp
         DEMO_DEST_DIR : "$web/mgplus/pr-${{ steps.package-version.outputs.current-version}}-${{ github.event.pull_request.number }}/demo"
         DIST_SOURCE_DIR : dist
         DIST_DEST_DIR : "$web/mgplus/pr-${{ steps.package-version.outputs.current-version}}-${{ github.event.pull_request.number }}/dist"
        with:
          azcliversion: 2.30.0
          inlineScript: |
           az extension add -n storage-preview -y
           az storage blob upload-batch -s  $DIST_SOURCE_DIR -d $DIST_DEST_DIR --account-name $ACCOUNT_NAME
           az storage blob upload-batch -s  $DEMO_SOURCE_DIR -d $DEMO_ROOT_DIR --account-name $ACCOUNT_NAME --pattern '[!node_modules&&src&&dom-plugins]'
           
           
  deploy_preview:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    name: build and deploy PR version
    permissions:
      contents: read            
      id-token: write 
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master
      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: "npm install, build, and test"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true 
      - name: deploy demo site to Azure static website
        uses: azure/CLI@v1     
        env: 
         ACCOUNT_NAME: stevodocs
         DEMO_SOURCE_DIR : src
         DEMO_DEST_DIR : "$web/mgplus/${{ steps.package-version.outputs.current-version}}-preview/demo"
         DIST_SOURCE_DIR : dist
         DIST_DEST_DIR : "$web/mgplus/${{ steps.package-version.outputs.current-version}}-preview/dist"
        with:
          azcliversion: 2.30.0
          inlineScript: |
           az extension add -n storage-preview -y
           az storage blob upload-batch -s  $DEMO_SOURCE_DIR -d $DEMO_DEST_DIR --account-name $ACCOUNT_NAME
           az storage blob upload-batch -s  $DIST_SOURCE_DIR -d $DIST_DEST_DIR --account-name $ACCOUNT_NAME
           
  
        
           



            
        
