# mgplus workflow

name: CI
env:
  AZURE_STORAGE_SERVICE_ENDPOINT: https://stevodocs.blob.core.windows.net/
  AZURE_STORAGE_AUTH_MODE: login
  AZURE_STORAGE_ACCOUNT_NAME: stevodocs
  AZURE_INDEX_DOCUMENT_NAME: index.html
  SOURCE_DIR: ./dist
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master 
jobs:
  # deploy pullrequest version of demo site
  deploy_pr_demo:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'    
    runs-on: ubuntu-latest
    name: build and deploy PR version
    permissions:
      contents: read            
      id-token: write 
    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master
      # - name: Setup Node 14.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: "14.x"
      # - name: "npm install, build, and test"
      #   run: |
      #     npm install
      #     npm run build --if-present
      #     npm run test --if-present
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true 
      - name: deploy demo site to Azure static website
        uses: azure/CLI@v1     
        env: 
         SOURCE_DIR : demo
         DEST_DIR : "$web/mgplus/${{ github.ref_name }}"
        with:
          azcliversion: 2.30.0
          inlineScript: |
           az extension add -n storage-preview -y
           az storage blob upload-batch -s  $SOURCE_DIR -d $DEST_DIR --account-name stevodocs
        
           



            
        
