# This is a basic workflow to help you get started with Actions

name: CI
env:
  AZURE_STORAGE_ACCOUNT_NAME: strsandbox2
  AZURE_INDEX_DOCUMENT_NAME: index.html
  SOURCE_DIR: ./dist
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [preview/*.*]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout the repo
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Setup Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: "npm install, build, and test"
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: "Deploy to Azure WebApp"
        uses: feeloor/azure-static-website-deploy@master
        env:
          SOURCE_DIR: ${{ env.SOURCE_DIR }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SECRET: ${{ secrets.AZURE_SECRET }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ env.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_INDEX_DOCUMENT_NAME: ${{ env.AZURE_INDEX_DOCUMENT_NAME }}
          AZURE_ERROR_DOCUMENT_NAME: ""
