# mgplus workflow

name: Azure CDN and deploy demo CI/CD
env:
  AZURE_STORAGE_SERVICE_ENDPOINT: https://stevodocs.blob.core.windows.net/
  AZURE_STORAGE_AUTH_MODE: login
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
jobs:
  deploy_pullrequest:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: CDN - deploy PR version
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: "build lib and deploy demo"
        id: "build_action"
        uses: ./.github/actions/build-action
        with:
          stage: "beta-${{ github.event.pull_request.number }}"
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: deploy demo app to Azure static website
        uses: azure/CLI@v1
        env:
          PACKAGE_VERSION: "${{ steps.build_action.outputs.package_version }}"
          ACCOUNT_NAME: stevodocs
          DEMO_ROOT_DIR: "$web"
          DEMO_SOURCE_DIR: demo_build
          DEMO_DEST_DIR: "$web/mgplus/demo/${{ steps.build_action.outputs.package_version }}"
          DIST_SOURCE_DIR: dist
          DIST_DEST_DIR: "mgpluscdn/${{ steps.build_action.outputs.package_version }}"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az extension add -n storage-preview -y
            az storage blob upload-batch -s  $DEMO_SOURCE_DIR -d $DEMO_DEST_DIR --account-name $ACCOUNT_NAME
            az storage blob upload-batch -s  $DIST_SOURCE_DIR -d $DIST_DEST_DIR --account-name $ACCOUNT_NAME
            az cdn endpoint purge -g rg-devops -n mgplus-demo --profile-name cdn-evo --content-paths '/*'
  deploy_preview:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/master') == true
    runs-on: ubuntu-latest
    name: CDN - deploy preview version
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: "build lib and deploy demo"
        uses: ./.github/actions/build-action
        id: "build_action"
        with:
          stage: "preview"
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: deploy demo site to Azure static website
        uses: azure/CLI@v1
        env:
          ACCOUNT_NAME: stevodocs
          DEMO_SOURCE_DIR: demo_build
          DEMO_DEST_DIR: "$web/mgplus/demo/${{ steps.build_action.outputs.package_version }}"
          DIST_SOURCE_DIR: dist
          DIST_DEST_DIR: "mgpluscdn/${{ steps.build_action.outputs.package_version }}"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az extension add -n storage-preview -y
            az storage blob upload-batch -s  $DEMO_SOURCE_DIR -d $DEMO_DEST_DIR --account-name $ACCOUNT_NAME
            az storage blob upload-batch -s  $DIST_SOURCE_DIR -d $DIST_DEST_DIR --account-name $ACCOUNT_NAME
  deploy_release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') == true
    runs-on: ubuntu-latest
    name: CDN - deploy release version
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: "build lib and deploy demo"
        uses: ./.github/actions/build-action
        id: "build_action"
        with:
          stage: "release"
      - name: azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: deploy demo site to Azure static website
        uses: azure/CLI@v1
        env:
          ACCOUNT_NAME: stevodocs
          DEMO_SOURCE_DIR: demo_build
          DEMO_DEST_DIR: "$web/mgplus/demo/${{ steps.build_action.outputs.package_base_version }}"
          DIST_SOURCE_DIR: dist
          DIST_DEST_DIR: "mgpluscdn/${{ steps.build_action.outputs.package_base_version }}"
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az extension add -n storage-preview -y
            az storage blob upload-batch -s  $DEMO_SOURCE_DIR -d $DEMO_DEST_DIR --account-name $ACCOUNT_NAME
            az storage blob upload-batch -s  $DIST_SOURCE_DIR -d $DIST_DEST_DIR --account-name $ACCOUNT_NAME
